version: "3.1"

services:
  OneDesk_postgres:
    container_name: OneDesk_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: OneDesk
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: OneDesk

  OneDesk:
    container_name: OneDesk
    build: "."
    ports:
      - 3000:3000
      - 5001:5003
    restart: always
    depends_on:
      - OneDesk_postgres
    environment:
      DB_USERNAME: "OneDesk"
      DB_PASSWORD: "1234"
      DB_HOST: "OneDesk_postgres"
      SECRET: 'OneDesk4life'
      
volumes: 
 pgdata: