version: "3.1"

services:
  OneDesk_postgres:
    container_name: OneDesk_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: OneDesk
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: OneDesk

  OneDesk:
    container_name: OneDesk
    image: pepperlabs/OneDesk:latest
    ports:
      - 1000:3000
      - 1001:5003
# If running via Docker on a hypervisor, enable DNS.
#    dns:
#      - 1.1.1.1
#      - 8.8.8.8
    restart: always
    depends_on:
      - OneDesk_postgres
    environment:
      DB_USERNAME: "OneDesk"
      DB_PASSWORD: "12345"
      DB_HOST: "OneDesk_postgres"
      SECRET: 'OneDesk4life'

volumes:
 pgdata_live:
